name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        ENVHELLOWORLD: ${{ secrets.HELLOWORLD }}
    steps: 
    - uses: actions/checkout@v2
    - name: Try Echo
      run: echo "$ENVHELLOWORLD"
      
    - name: Try Echo 2
      run: echo "${{ secrets.HELLOWORLD }}"
    
